{
  "openapi": "3.0.1",
  "info": {
    "title": "Default module",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/api/user/{:id}": {
      "get": {
        "summary": "get user by id",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": ":id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      },
      "delete": {
        "summary": "delete user",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": ":id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      },
      "put": {
        "summary": "update user",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": ":id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": "{}{% faker internet.userName %}"
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/user": {
      "post": {
        "summary": "new user",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "Username": {
                    "type": "string"
                  }
                },
                "required": [
                  "Username"
                ]
              },
              "example": {
                "username": "Sev"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      },
      "get": {
        "summary": "get all users",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/account/login": {
      "post": {
        "summary": "Login",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "email": "email@email.com",
                "password": "password"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/account/register": {
      "post": {
        "summary": "Register",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "username": "username",
                "email": "email@email.com",
                "password": "password",
                "termsOfUse": true,
                "privacyPolicy": true
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/api/account/forgot-password": {
      "post": {
        "summary": "ForgotPassword",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "email": "zali2008@wp.pl",
                "clientURI": "https://localhost:4200"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/account/reset-password": {
      "post": {
        "summary": "ResetPassword",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJ6YWxpMjAwOEB3cC5wbCIsImp0aSI6IjBlZDdkMzgzLTcwNTktNDI4Yi05ZjFjLWI2MTdmZjFjMDYwOSIsIlRva2VuVHlwZSI6IlBhc3N3b3JkUmVzZXQiLCJuYmYiOjE3Mzg4MzU1NzIsImV4cCI6MTczODkyMTk3MiwiaWF0IjoxNzM4ODM1NTcyfQ.PkuRi_1QY4LB1bWiZI3AwfTuUptLajYAwtmZDW32OZzpkYtNzyWQaJIliDKpjtSQCI44blqbDWqQkgnhUqitAA",
                "email": "zali2008@wp.pl",
                "password": "password",
                "confirmPassword": "password"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/product": {
      "post": {
        "summary": "CreateProduct",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "name": "Cynamon",
                "producent": "Sypka cynamonka",
                "createdBy": "Admin"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "put": {
        "summary": "UpdateProduct",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "id": "67a601a35a3647b148a0442a",
                "name": "Jabłko",
                "producent": "Jabłczane Imperium",
                "createdBy": "Admin",
                "updatedBy": "Sevuu"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "get": {
        "summary": "GetAllProducts",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InphbGkyMDA4QHdwLnBsIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiU2V2dXUiLCJuYmYiOjE3Mzk1MjcyNDksImV4cCI6MTc0MDEzMjA0OSwiaWF0IjoxNzM5NTI3MjQ5fQ._8baeZFWcFlnGBgCWgxYD5NLWTkUr2ewFgHDKp_cL8RJCwANndhjSIgYly4on5LJPSh3ZUY16T7oUvuU3ypy8w",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "405": {
            "description": "",
            "content": {
              "application/octet-stream": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/product/{id}": {
      "get": {
        "summary": "GetProduct",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "67a601a35a3647b148a0442a",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InphbGkyMDA4QHdwLnBsIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiU2V2dXUiLCJuYmYiOjE3Mzk1MjcyNDksImV4cCI6MTc0MDEzMjA0OSwiaWF0IjoxNzM5NTI3MjQ5fQ._8baeZFWcFlnGBgCWgxYD5NLWTkUr2ewFgHDKp_cL8RJCwANndhjSIgYly4on5LJPSh3ZUY16T7oUvuU3ypy8w",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "producent": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "producent"
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "delete": {
        "summary": "DeleteProduct",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "67a5f6fbd7170b280a229492",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/product/items": {
      "get": {
        "summary": "SearchProductByPattern",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "searchPattern",
            "in": "query",
            "description": "",
            "required": false,
            "example": "mara",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "producent": {
                        "type": "string"
                      },
                      "createdBy": {
                        "type": "string"
                      },
                      "updatedBy": {
                        "type": "string",
                        "nullable": true
                      }
                    },
                    "required": [
                      "id",
                      "name",
                      "producent",
                      "createdBy",
                      "updatedBy"
                    ]
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/recipe": {
      "post": {
        "summary": "CreateRecipe",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "name": "Pieczone jabłko",
                "duration": "15",
                "productsId": [
                  "67a601a35a3647b148a0442a"
                ],
                "createdBy": "Admin",
                "steps": [
                  {
                    "order": 1,
                    "content": "Obierz jabłka",
                    "productsId": [
                      "67a601a35a3647b148a0442a"
                    ],
                    "duration": 15
                  },
                  {
                    "order": 2,
                    "content": "Włóż jabłka do piekarnika",
                    "duration": 25
                  },
                  {
                    "order": 3,
                    "content": "Wyjmij jabłka z piekarnika",
                    "duration": 5
                  }
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "get": {
        "summary": "GetAllRecipes",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "duration": {
                        "type": "integer"
                      },
                      "products": {
                        "type": "null"
                      },
                      "mealType": {
                        "type": "integer"
                      },
                      "steps": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "order": {
                              "type": "integer"
                            },
                            "content": {
                              "type": "string"
                            },
                            "productsId": {
                              "type": "array",
                              "items": {
                                "type": "string"
                              },
                              "nullable": true
                            },
                            "duration": {
                              "type": "integer"
                            }
                          },
                          "required": [
                            "order",
                            "content",
                            "productsId",
                            "duration"
                          ]
                        }
                      }
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "put": {
        "summary": "UpdateRecipe",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "id": "67b33c07716237b0a82fe3f8",
                "name": "Pieczone jabłko",
                "duration": "15",
                "productIds": [
                  "67a601a35a3647b148a0442a",
                  "67c2fdea087c2bc589b0829e"
                ],
                "updatedBy": "Master Admin",
                "steps": [
                  {
                    "order": 1,
                    "content": "Obierz jabłka",
                    "productIds": [
                      "67a601a35a3647b148a0442a",
                      "67c2fdea087c2bc589b0829e"
                    ],
                    "duration": 15
                  },
                  {
                    "order": 2,
                    "content": "Włóż jabłka do piekarnika",
                    "duration": 25
                  },
                  {
                    "order": 3,
                    "content": "Wyjmij jabłka z piekarnika",
                    "duration": 5
                  }
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/recipe/{id}": {
      "get": {
        "summary": "GetRecipe",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "duration": {
                      "type": "integer"
                    },
                    "products": {
                      "type": "array",
                      "items": {
                        "type": "object"
                      }
                    },
                    "mealType": {
                      "type": "integer"
                    },
                    "steps": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "order": {
                            "type": "integer"
                          },
                          "content": {
                            "type": "string"
                          },
                          "productsId": {
                            "type": "array",
                            "items": {
                              "type": "string"
                            },
                            "nullable": true
                          },
                          "duration": {
                            "type": "integer"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "security": []
      },
      "delete": {
        "summary": "DeleteRecipe",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/menus/generate": {
      "post": {
        "summary": "GenerateMenu",
        "deprecated": false,
        "description": "Generates a weekly menu PDF based on meal configurations",
        "tags": ["Menu"],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "meals": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "type": {
                          "type": "integer",
                          "description": "MealType enum: 0=Breakfast, 1=Dinner, 2=Lunch, 3=Appetizer, 4=Dessert"
                        },
                        "name": {
                          "type": "string"
                        },
                        "time": {
                          "type": "string"
                        },
                        "enabled": {
                          "type": "boolean"
                        }
                      },
                      "required": ["type", "name", "time", "enabled"]
                    }
                  }
                },
                "required": ["meals"]
              },
              "example": {
                "meals": [
                  {
                    "type": 0,
                    "name": "Śniadanie",
                    "time": "08:00",
                    "enabled": true
                  },
                  {
                    "type": 2,
                    "name": "Obiad",
                    "time": "13:00",
                    "enabled": true
                  },
                  {
                    "type": 1,
                    "name": "Kolacja",
                    "time": "18:00",
                    "enabled": true
                  }
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "PDF file with generated menu",
            "content": {
              "application/pdf": {
                "schema": {
                  "type": "string",
                  "format": "binary"
                }
              }
            }
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "responses": {},
    "securitySchemes": {}
  },
  "servers": [],
  "security": []
}